title: "Jörg Pfründer"
description: "About Software and IT"
url: "https://joerg-pfruender.github.io/"
twitter_username: joergpfruender
github_username:  joerg-pfruender

theme: minima
plugins:
  - jekyll-feed